// types to use for the ti-basic AST
// ==================

export const NUMBER = 'number'
export const BINARY = 'binary'
export const UNARY = 'unary'
export const VARIABLE = 'variable'
export const STRING = 'string'
export const ANS = 'ans'
export const ValueStatement = 'value'
export const AssignmentStatement = 'assign'
export const IfStatement = 'if'
export const Display = 'display'
export const ThenStatement = 'ThenStatement'
export const ElseStatement = 'ElseStatement'
export const ForLoop = 'ForLoop'
export const WhileLoop = 'WhileLoop'
export const RepeatLoop = 'RepeatLoop'
export const EndStatement = 'EndStatement'
export const PauseStatement = 'PauseStatement'
export const LabelStatement = 'LabelStatement'
export const GotoStatement = 'GotoStatement'
export const IncrementSkip = 'IncrementSkip'
export const DecrementSkip = 'DecrementSkip'
export const MenuStatement = 'MenuStatement'
export const ProgramStatement = 'ProgramStatement'
export const ReturnStatement = 'ReturnStatement'
export const StopStatement = 'StopStatement'
export const DelVarStatement = 'DelVarStatement'
export const GraphStyleStatement = 'GraphStyleStatement'
export const OpenLibStatement = 'OpenLibStatement'
export const ExecLibStatement = 'ExecLibStatement'
export const Prompt = 'Prompt'
export const SyntaxError = 'SyntaxError'
